# Use a base image with Python
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the Docker app script
COPY client.py /app/

# Run the Docker app when the container starts
CMD ["python", "client.py"]